---
# tasks/main.yml

- name: lineinfile | update licence key
  lineinfile:
    path: "/etc/newrelic-infra.yml"
    line: "license_key: {{ newrelic.license }}"
    state: "present"
    create: "yes"

- name: apt_key | add newrelic repository key
  apt_key:
    url: "https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg"

- name: apt_repository | add thirdparty repositories
  apt_repository:
    repo: "{{ item }}"
    state: "present"
  with_items:
    - "deb [arch=amd64] http://download.newrelic.com/infrastructure_agent/linux/apt trusty main"

- name: apt | install packages
  apt:
    name: "{{ item }}"
    state: "present"
    update_cache: "yes"
  with_items:
    - "newrelic-infra"

- name: user | add newrelic user to docker group if docker is presented
  user:
    name: "{{ item }}"
    append: "yes"
    groups: "docker"
  with_items:
    - "newrelic"
  ignore_errors: "yes"

- name: lineinfile | update newrelic configuration
  lineinfile:
    dest: "/etc/newrelic/nrsysmond.cfg"
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_items:
    - { key: "hostname", value: "iprice-{{ app_env }}-{{ group_names | join('') }}" }
    - { key: "license_key", value: "{{ newrelic.license }}" }

- name: service | restart newrelic-sysmond daemon
  service:
    name: "newrelic-infra"
    state: "restarted"
    enabled: "yes"
